/* Admin data-quality dashboard */
(function(){
  "use strict";
  let qualityRows=[],qualitySongs=[];
  function norm(v){return String(v||"").normalize("NFKC").toLowerCase().replace(/[^\p{L}\p{N}]+/gu,"");}
  async function req(path,options={}){return adminFeedbackRequest(path,options);}
  function install(){
    const panel=document.querySelector("#adminPanel");if(!panel||document.querySelector("#qualityDashboard"))return;
    const heading=[...panel.children].find(x=>x.tagName==="H2"&&x.textContent.includes("登録曲"));
    heading?.insertAdjacentHTML("beforebegin",`<section id="qualityDashboard" class="panel"><h2>データ品質ダッシュボード</h2><div class="quality-summary" id="qualitySummary"></div><div class="quality-actions"><button id="loadDuplicates" type="button">重複候補を検出</button><button id="loadVideoQueue" type="button">動画の再確認対象</button><button id="loadQualityReports" type="button">利用者からの曲報告</button></div><p id="qualityStatus" class="status"></p><div id="qualityResults" class="song-list"></div></section>`);
    document.querySelector("#loadDuplicates")?.addEventListener("click",showDuplicates);
    document.querySelector("#loadVideoQueue")?.addEventListener("click",showVideoQueue);
    document.querySelector("#loadQualityReports")?.addEventListener("click",loadReports);
    document.querySelector("#qualityResults")?.addEventListener("click",qualityAction);
  }
  function rows(){return qualitySongs.length?qualitySongs:(Array.isArray(adminSongs)?adminSongs:[]);}
  function summary(){const s=document.querySelector("#qualitySummary");if(!s)return;const all=rows(),unchecked=all.filter(x=>(x.youtube_status||"unchecked")==="unchecked").length,low=all.filter(x=>x.ai_tag_confidence!=null&&Number(x.ai_tag_confidence)<.65).length;s.innerHTML=`<span>登録 ${all.length}曲</span><span>動画未確認 ${unchecked}曲</span><span>AIタグ低信頼 ${low}曲</span>`;}
  function showDuplicates(){const groups=new Map();rows().forEach(s=>{const k=norm(s.artist_en||s.artist)+"|"+norm(s.title_en||s.title);if(k!=="|")groups.set(k,[...(groups.get(k)||[]),s]);});const dup=[...groups.values()].filter(g=>g.length>1);document.querySelector("#qualityResults").innerHTML=dup.length?dup.map(g=>`<article class="song-row"><div class="song-copy"><span class="badge">重複候補 ${g.length}件</span>${g.map(s=>`<p><strong>${escapeHtml(s.title)}</strong> — ${escapeHtml(s.artist)} · ID ${s.id}</p>`).join("")}</div></article>`).join(""):"<p>重複候補はありません。</p>";}
  function showVideoQueue(){const stale=rows().filter(s=>!s.youtube_checked_at||Date.now()-new Date(s.youtube_checked_at).getTime()>30*86400000||(s.youtube_status&&s.youtube_status!=="valid"));document.querySelector("#qualityResults").innerHTML=stale.slice(0,100).map(s=>`<article class="song-row"><div class="song-copy"><span class="badge">${escapeHtml(s.youtube_status||"unchecked")}</span><h3>${escapeHtml(s.title)}</h3><p>${escapeHtml(s.artist)}</p></div><div class="song-actions"><a href="${escapeHtml(s.youtube_url||"#")}" target="_blank" rel="noopener">YouTube確認</a><button data-song-check="${s.id}" data-state="valid">有効</button><button data-song-check="${s.id}" data-state="unavailable" class="danger">無効</button></div></article>`).join("")||"<p>再確認対象はありません。</p>";}
  async function loadReports(){try{qualityRows=await req("song_quality_reports?select=id,song_id,report_type,message,status,created_at&status=eq.pending&order=created_at.desc&limit=200");document.querySelector("#qualityResults").innerHTML=qualityRows.map(r=>{const s=rows().find(x=>Number(x.id)===Number(r.song_id));return `<article class="song-row"><div class="song-copy"><span class="badge">${escapeHtml(r.report_type)}</span><h3>${escapeHtml(s?.title||("曲ID "+r.song_id))}</h3><p>${escapeHtml(r.message||"")}</p></div><div class="song-actions"><button data-report-resolve="${r.id}">解決済みにする</button></div></article>`;}).join("")||"<p>未対応の報告はありません。</p>";}catch(e){document.querySelector("#qualityStatus").textContent=e.message;}}
  async function qualityAction(e){const check=e.target.closest("[data-song-check]"),resolve=e.target.closest("[data-report-resolve]");try{if(check){await req(`songs?id=eq.${Number(check.dataset.songCheck)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({youtube_status:check.dataset.state,youtube_checked_at:new Date().toISOString(),data_quality_status:check.dataset.state==="valid"?"verified":"needs_review"})});showVideoQueue();}if(resolve){await req(`song_quality_reports?id=eq.${Number(resolve.dataset.reportResolve)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({status:"resolved",updated_at:new Date().toISOString()})});loadReports();}}catch(err){document.querySelector("#qualityStatus").textContent=err.message;}}
  const oldLoad=loadSongs;loadSongs=async function(){await oldLoad();try{qualitySongs=await req("songs?select=id,title,artist,title_en,artist_en,youtube_url,youtube_status,youtube_checked_at,ai_tag_confidence,data_quality_status&order=id.asc");}catch(e){qualitySongs=[];}summary();};
  const oldFeedback=renderAdminFeedback;renderAdminFeedback=function(){adminFeedbackRows.sort((a,b)=>{const count=x=>adminFeedbackRows.filter(r=>norm(r.message)===norm(x.message)).length;return count(b)-count(a)||new Date(b.created_at)-new Date(a.created_at);});oldFeedback();document.querySelectorAll(".feedback-admin-row").forEach((el,i)=>{const row=adminFeedbackRows[i],votes=adminFeedbackRows.filter(r=>norm(r.message)===norm(row.message)).length;el.querySelector(".song-copy")?.insertAdjacentHTML("afterbegin",`<span class="badge">類似要望 ${votes}票</span>`);});};
  install();
})();
