/* Discovery Club: one home for missions, reactions, recognition and live discovery. */
(function(){
"use strict";
const I={
 ja:{nav:"クラブ",title:"JHG Discovery Club",copy:"聴く、発掘する、つながる。毎日の参加がJ-POPを世界へ広げます。",missions:"ミッション",reactions:"リアクション",leaders:"発掘者",follow:"フォロー",playlists:"プレイリスト",events:"週間企画",regions:"地域発見",timeline:"タイムライン",next:"次の一曲",today:"今日のミッション",listen:"未知の曲を聴く",react:"曲にリアクションする",save:"曲をお気に入りにする",go:"始める",done:"達成",badges:"称号",early:"早期発掘",empty:"まだ活動がありません。",community:"コメントと交流",open:"開く",points:"pt",week:"今週のテーマ",regionTitle:"今週、各地域が発見した曲",nextTitle:"あなたの次の一曲",more:"似た曲をもっと見る",first_time:"初めて知った",deserves_more:"もっと評価されるべき",want_context:"背景を知りたい",would_travel:"自分の国でも流行りそう",reactTitle:"この曲をどう感じた？",login:"参加記録はアカウントに安全に保存されます。"},
 en:{nav:"Club",title:"JHG Discovery Club",copy:"Listen, discover and connect. Every action helps J-pop travel further.",missions:"Missions",reactions:"Reactions",leaders:"Discoverers",follow:"Following",playlists:"Playlists",events:"Weekly event",regions:"Regions",timeline:"Timeline",next:"Next song",today:"Today's missions",listen:"Listen to an unknown song",react:"React to a song",save:"Save a hidden gem",go:"Start",done:"Done",badges:"Badges",early:"Early discoveries",empty:"No activity yet.",community:"Comments and community",open:"Open",points:"pts",week:"This week's theme",regionTitle:"What each region discovered this week",nextTitle:"Your next song",more:"Find more similar songs",first_time:"First time hearing it",deserves_more:"Deserves more attention",want_context:"I want the context",would_travel:"Could travel in my country",reactTitle:"How did this song feel?",login:"Your participation is safely saved to your account."},
 ko:{nav:"클럽",title:"JHG 디스커버리 클럽",copy:"듣고, 발견하고, 연결하세요. 모든 참여가 J-pop을 더 멀리 전합니다.",missions:"미션",reactions:"반응",leaders:"발굴자",follow:"팔로잉",playlists:"플레이리스트",events:"주간 이벤트",regions:"지역",timeline:"타임라인",next:"다음 곡",today:"오늘의 미션",listen:"처음 듣는 곡 듣기",react:"곡에 반응하기",save:"숨은 명곡 저장",go:"시작",done:"완료",badges:"배지",early:"초기 발견",empty:"아직 활동이 없습니다.",community:"댓글과 커뮤니티",open:"열기",points:"점",week:"이번 주 테마",regionTitle:"이번 주 지역별 발견",nextTitle:"다음 추천곡",more:"비슷한 곡 더 찾기",first_time:"처음 들었어요",deserves_more:"더 주목받아야 해요",want_context:"배경을 알고 싶어요",would_travel:"우리 나라에서도 통할 것 같아요",reactTitle:"이 곡을 어떻게 느꼈나요?",login:"참여 기록은 계정에 안전하게 저장됩니다."},
 zh:{nav:"俱乐部",title:"JHG发现俱乐部",copy:"聆听、发现、连接。每次参与都让J-pop走得更远。",missions:"任务",reactions:"反应",leaders:"发现者",follow:"关注",playlists:"播放列表",events:"每周活动",regions:"地区",timeline:"动态",next:"下一首",today:"今日任务",listen:"听一首陌生歌曲",react:"对歌曲作出反应",save:"收藏隐藏名曲",go:"开始",done:"完成",badges:"徽章",early:"早期发现",empty:"暂无活动。",community:"评论与社区",open:"打开",points:"分",week:"本周主题",regionTitle:"本周各地区的发现",nextTitle:"你的下一首歌",more:"发现更多相似歌曲",first_time:"第一次听",deserves_more:"值得更多关注",want_context:"想了解背景",would_travel:"可能会在我的国家流行",reactTitle:"你对这首歌有什么感觉？",login:"参与记录将安全保存到你的账户。"},
 ru:{nav:"Клуб",title:"Клуб открытий JHG",copy:"Слушайте, открывайте и общайтесь. Каждое действие помогает J-pop идти дальше.",missions:"Задания",reactions:"Реакции",leaders:"Первооткрыватели",follow:"Подписки",playlists:"Плейлисты",events:"Событие недели",regions:"Регионы",timeline:"Лента",next:"Следующий трек",today:"Задания дня",listen:"Послушать незнакомую песню",react:"Оставить реакцию",save:"Сохранить находку",go:"Начать",done:"Готово",badges:"Значки",early:"Ранние открытия",empty:"Активности пока нет.",community:"Комментарии и сообщество",open:"Открыть",points:"очк.",week:"Тема недели",regionTitle:"Находки регионов на этой неделе",nextTitle:"Ваш следующий трек",more:"Больше похожих песен",first_time:"Слышу впервые",deserves_more:"Заслуживает внимания",want_context:"Хочу узнать контекст",would_travel:"Может стать популярной у нас",reactTitle:"Как вам эта песня?",login:"Ваше участие безопасно сохраняется в аккаунте."},
 es:{nav:"Club",title:"Club de descubrimiento JHG",copy:"Escucha, descubre y conecta. Cada acción ayuda al J-pop a llegar más lejos.",missions:"Misiones",reactions:"Reacciones",leaders:"Descubridores",follow:"Siguiendo",playlists:"Listas",events:"Evento semanal",regions:"Regiones",timeline:"Actividad",next:"Siguiente canción",today:"Misiones de hoy",listen:"Escuchar una canción desconocida",react:"Reaccionar a una canción",save:"Guardar una joya",go:"Empezar",done:"Hecho",badges:"Insignias",early:"Descubrimientos tempranos",empty:"Aún no hay actividad.",community:"Comentarios y comunidad",open:"Abrir",points:"pts",week:"Tema de esta semana",regionTitle:"Lo descubierto por cada región",nextTitle:"Tu siguiente canción",more:"Encontrar canciones similares",first_time:"La escucho por primera vez",deserves_more:"Merece más atención",want_context:"Quiero conocer el contexto",would_travel:"Podría triunfar en mi país",reactTitle:"¿Qué te hizo sentir?",login:"Tu participación se guarda de forma segura en tu cuenta."},
 fr:{nav:"Club",title:"Club de découverte JHG",copy:"Écoutez, découvrez et échangez. Chaque action aide la J-pop à voyager.",missions:"Missions",reactions:"Réactions",leaders:"Découvreurs",follow:"Abonnements",playlists:"Playlists",events:"Événement de la semaine",regions:"Régions",timeline:"Fil d’activité",next:"Titre suivant",today:"Missions du jour",listen:"Écouter un titre inconnu",react:"Réagir à un titre",save:"Enregistrer une pépite",go:"Commencer",done:"Terminé",badges:"Badges",early:"Découvertes précoces",empty:"Aucune activité pour le moment.",community:"Commentaires et communauté",open:"Ouvrir",points:"pts",week:"Thème de la semaine",regionTitle:"Les découvertes de chaque région",nextTitle:"Votre prochain titre",more:"Trouver des titres similaires",first_time:"Première écoute",deserves_more:"Mérite plus d’attention",want_context:"Je veux comprendre le contexte",would_travel:"Pourrait marcher dans mon pays",reactTitle:"Que vous inspire ce titre ?",login:"Votre participation est enregistrée en toute sécurité."}
};
const E={
 ja:{artists:"アーティスト",tags:"タグとジャンル",collectionLabel:"コレクション",collectionCopy:"自分だけのテーマで曲をまとめ、共有できます。",firstFind:"最初の発見",listens10:"10曲試聴",reactions10:"10リアクション",early5:"早期発掘×5",weeklyStreak:"週間継続",ambassador:"アンバサダー",early_discovery:"誰より早く発掘しました",listener:"JHGリスナー",eventHidden80s:"80年代の隠れた名曲週間"},
 en:{artists:"Artists",tags:"Tags & genres",collectionLabel:"Collections",collectionCopy:"Build and share collections around your own theme.",firstFind:"First Find",listens10:"10 Listens",reactions10:"10 Reactions",early5:"Early ×5",weeklyStreak:"Weekly Streak",ambassador:"Ambassador",early_discovery:"Found it early",listener:"JHG Listener",eventHidden80s:"Hidden 80s Week"},
 ko:{artists:"아티스트",tags:"태그와 장르",collectionLabel:"컬렉션",collectionCopy:"나만의 테마로 곡을 모아 공유하세요.",firstFind:"첫 발견",listens10:"10곡 듣기",reactions10:"반응 10회",early5:"초기 발견×5",weeklyStreak:"주간 연속",ambassador:"앰배서더",early_discovery:"남들보다 먼저 발견했습니다",listener:"JHG 리스너",eventHidden80s:"숨은 80년대 명곡 주간"},
 zh:{artists:"艺人",tags:"标签与曲风",collectionLabel:"歌单合集",collectionCopy:"按自己的主题整理并分享歌曲。",firstFind:"首次发现",listens10:"试听10首",reactions10:"10次反应",early5:"早期发现×5",weeklyStreak:"每周连续",ambassador:"推广大使",early_discovery:"抢先发现了这首歌",listener:"JHG听众",eventHidden80s:"80年代隐藏名曲周"},
 ru:{artists:"Исполнители",tags:"Теги и жанры",collectionLabel:"Подборки",collectionCopy:"Собирайте и делитесь подборками на свою тему.",firstFind:"Первая находка",listens10:"10 прослушиваний",reactions10:"10 реакций",early5:"5 ранних находок",weeklyStreak:"Недельная серия",ambassador:"Амбассадор",early_discovery:"Открыл раньше других",listener:"Слушатель JHG",eventHidden80s:"Неделя скрытых хитов 80-х"},
 es:{artists:"Artistas",tags:"Etiquetas y géneros",collectionLabel:"Colecciones",collectionCopy:"Crea y comparte colecciones con tu propio tema.",firstFind:"Primer hallazgo",listens10:"10 escuchas",reactions10:"10 reacciones",early5:"5 hallazgos tempranos",weeklyStreak:"Racha semanal",ambassador:"Embajador",early_discovery:"La descubrió antes que otros",listener:"Oyente de JHG",eventHidden80s:"Semana de joyas ocultas de los 80"},
 fr:{artists:"Artistes",tags:"Tags et genres",collectionLabel:"Sélections",collectionCopy:"Créez et partagez des sélections selon votre thème.",firstFind:"Première découverte",listens10:"10 écoutes",reactions10:"10 réactions",early5:"5 découvertes précoces",weeklyStreak:"Série hebdomadaire",ambassador:"Ambassadeur",early_discovery:"Découvert avant les autres",listener:"Auditeur JHG",eventHidden80s:"Semaine des pépites des années 80"}
};
const t=k=>(I[interfaceLanguage]||I.en)[k]||(E[interfaceLanguage]||E.en)[k]||I.en[k]||E.en[k]||k,s=v=>escapeHtml(String(v??"")),byId=id=>songs.find(x=>Number(x.id)===Number(id));
const state={tab:"missions",actions:[],badges:[],feed:[]};
const tabs=["missions","reactions","leaders","follow","playlists","events","regions","timeline","next"];
VALID_VIEWS.add("club");
function nav(){const n=document.querySelector(".primary-nav"),l=document.querySelector(".language-control");if(!n||n.querySelector("[data-club-route]"))return;const b=document.createElement("button");b.type="button";b.className="nav-item";b.dataset.clubRoute="club";b.textContent=t("nav");b.onclick=()=>navigateTo("club");n.insertBefore(b,l);}
function install(){nav();document.querySelector("main")?.insertAdjacentHTML("beforeend",`<section class="shell section screen-panel club-screen" data-screen="club"><div class="club-hero"><div><p class="eyebrow dark">JHG DISCOVERY CLUB</p><h2 id="clubTitle"></h2><p id="clubCopy" class="section-copy"></p></div><p class="meta">${s(t("login"))}</p></div><div id="clubTabs" class="club-tabs"></div><div id="clubArea"></div></section>`);localize();document.addEventListener("click",click);}
function localize(){nav();const a=document.querySelector("[data-club-route]"),h=document.querySelector("#clubTitle"),p=document.querySelector("#clubCopy");if(a)a.textContent=t("nav");if(h)h.textContent=t("title");if(p)p.textContent=t("copy");renderTabs();}
function renderTabs(){const e=document.querySelector("#clubTabs");if(e)e.innerHTML=tabs.map(k=>`<button type="button" data-club-tab="${k}" class="${state.tab===k?'is-active':''}">${s(t(k))}</button>`).join("");}
async function api(path,o={}){return rest(path,{authenticated:true,...o})}
async function hub(){await show(state.tab)}
async function show(tab){state.tab=tab;renderTabs();const a=document.querySelector("#clubArea");if(!a)return;a.innerHTML='<p class="muted">Loading…</p>';try{await ({missions,reactions,leaders,follow,playlists,events,regions,timeline,next}[tab]||missions)(a)}catch(e){a.innerHTML=`<p class="form-error">${s(e.message)}</p>`}}
function cover(song){return song?songArtwork(song,"rising-cover"):"<span></span>"}
async function missions(a){const today=new Date().toISOString().slice(0,10);state.actions=await api(`discovery_club_actions?select=action,song_id&user_id=eq.${currentUser.id}&action_date=eq.${today}`).catch(()=>[]);state.badges=await api(`user_badges?select=badge_key,awarded_at&user_id=eq.${currentUser.id}`).catch(()=>[]);const defs=[['listen','listen','discover'],['react','react','ranking'],['favorite','save','favorites']];a.innerHTML=`<h3>${t("today")}</h3><div class="club-grid">${defs.map(([action,label,view])=>{const done=state.actions.some(x=>x.action===action);return `<article class="mission-card"><strong>${s(t(label))}</strong><div class="mission-progress"><span style="width:${done?100:0}%"></span></div><button class="action ${done?'':'primary'}" data-mission-view="${view}">${done?t("done"):t("go")}</button></article>`}).join("")}</div><h3>${t("badges")}</h3><div class="badge-grid">${[['first_find','🔎','firstFind'],['listener_10','🎧','listens10'],['reaction_10','💬','reactions10'],['early_5','⚡','early5'],['week_streak','🔥','weeklyStreak'],['ambassador','🌏','ambassador']].map(([k,i,n])=>`<article class="badge-card ${state.badges.some(b=>b.badge_key===k)?'is-earned':''}"><span class="badge-icon">${i}</span><strong>${t(n)}</strong></article>`).join("")}</div>`}
async function reactions(a){const pool=songs.filter(x=>!x.is_hidden).sort(()=>Math.random()-.5).slice(0,6);a.innerHTML=`<h3>${t("reactions")}</h3><div class="club-grid">${pool.map(x=>`<article class="club-card">${songArtwork(x,"editorial-cover")}<h3>${s(songTitle(x))}</h3><p>${s(songArtist(x))}</p><button class="action primary" data-song="${x.id}">${t("open")}</button></article>`).join("")}</div><button class="button button-ghost" data-club-community>${t("community")}</button>`}
async function leaders(a){const rows=await api("rpc/get_discovery_club_leaderboard",{method:"POST",body:'{"p_limit":25}'}).catch(()=>[]);a.innerHTML=`<h3>${t("leaders")}</h3><div class="club-leaderboard">${rows.map((x,i)=>`<article class="club-rank"><span>${String(i+1).padStart(2,'0')}</span><div><strong>${s(x.display_name)}</strong><small>@${s(x.handle)} · ${x.early_count} ${t("early")}</small></div><b>${x.points} ${t("points")}</b></article>`).join("")||`<p>${t("empty")}</p>`}</div>`}
function follow(a){a.innerHTML=`<div class="club-grid"><article class="club-card"><h3>${t("community")}</h3><p>${t("follow")}</p><button class="button" data-route="community">${t("open")}</button></article><article class="club-card"><h3>${t("follow")}</h3><p>${t("artists")}</p><button class="button" data-route="artists">${t("open")}</button></article><article class="club-card"><h3>${t("tags")}</h3><button class="button" data-route="genres">${t("open")}</button></article></div>`}
function playlists(a){a.innerHTML=`<div class="event-banner"><p class="eyebrow">JHG · ${t("collectionLabel")}</p><h3>${t("playlists")}</h3><p>${t("collectionCopy")}</p><button class="button" data-route="playlists">${t("open")}</button></div>`}
async function events(a){const rows=await api("weekly_discovery_events?select=*&is_active=eq.true&order=starts_at.desc&limit=3").catch(()=>[]),w=await api("rpc/get_weekly_hidden_gems",{method:"POST",body:'{"p_limit":8}'}).catch(()=>[]);a.innerHTML=`<h3>${t("week")}</h3>${rows.map(x=>`<article class="event-banner"><p>${new Date(x.starts_at).toLocaleDateString()} – ${new Date(x.ends_at).toLocaleDateString()}</p><h3>${s(x.event_key==='launch-hidden-80s'?t("eventHidden80s"):(interfaceLanguage==='ja'?x.title_ja:x.title_en))}</h3></article>`).join("")}<div class="club-grid">${w.map(x=>{const q=byId(x.song_id);return q?`<article class="club-card">${songArtwork(q,"editorial-cover")}<strong>${s(songTitle(q))}</strong><small>${s(songArtist(q))}</small><button class="action" data-song="${q.id}">${t("open")}</button></article>`:""}).join("")}</div>`}
async function regions(a){const rows=await api("rpc/get_region_discovery_challenge",{method:"POST",body:"{}"}).catch(()=>[]),max=Math.max(1,...rows.map(x=>Number(x.points)));a.innerHTML=`<h3>${t("regionTitle")}</h3><div class="region-bars">${rows.map((x,i)=>`<article class="region-row"><strong>${i+1}. ${s(x.region)}</strong><meter min="0" max="${max}" value="${x.points}"></meter><b>${x.points}</b></article>`).join("")||`<p>${t("empty")}</p>`}</div>`}
async function timeline(a){state.feed=await api("rpc/get_discovery_club_feed",{method:"POST",body:'{"p_limit":50}'}).catch(()=>[]);a.innerHTML=`<h3>${t("timeline")}</h3><div class="activity-list">${state.feed.map(x=>{const q=byId(x.song_id),label=t(x.message_key)||x.message_key;return `<article class="activity-row">${cover(q)}<div><strong>${s(x.display_name||x.handle||t('listener'))}</strong><p>${s(label)}${q?` · ${s(songTitle(q))}`:""}</p></div><time>${new Date(x.created_at).toLocaleDateString()}</time></article>`}).join("")||`<p>${t("empty")}</p>`}</div>`}
async function next(a){const pool=(personalizedRecommendations?.length?personalizedRecommendations:songs).filter(x=>!x.is_hidden).slice(0,12);a.innerHTML=`<h3>${t("nextTitle")}</h3><div class="club-grid">${pool.map(x=>`<article class="club-card">${songArtwork(x,"editorial-cover")}<strong>${s(songTitle(x))}</strong><small>${s(songArtist(x))}</small><button class="action primary" data-song="${x.id}">${t("open")}</button><button class="action" data-similar-song="${x.id}">${t("more")}</button></article>`).join("")}</div>`}
async function record(action,id=null){return api("rpc/record_club_action",{method:"POST",body:JSON.stringify({p_action:action,p_song_id:id})}).catch(()=>null)}
async function detailReactions(id){const root=document.querySelector("#songDetailFeature"),song=byId(id);if(!root||!song)return;root.querySelector(".reaction-panel")?.remove();const rows=await api("rpc/get_song_reaction_summary",{method:"POST",body:JSON.stringify({p_song_id:Number(id)})}).catch(()=>[]),map=new Map(rows.map(x=>[x.reaction,x]));root.insertAdjacentHTML("beforeend",`<section class="shell reaction-panel"><h3>${t("reactTitle")}</h3><div class="reaction-buttons">${['first_time','deserves_more','want_context','would_travel'].map(k=>{const r=map.get(k);return `<button data-club-react="${k}" data-song-id="${id}" class="${r?.my_reacted?'is-active':''}">${t(k)} · ${r?.reaction_count||0}</button>`}).join("")}</div></section>`)}
async function click(e){const tab=e.target.closest("[data-club-tab]"),mission=e.target.closest("[data-mission-view]"),route=e.target.closest("[data-route]"),song=e.target.closest("[data-song]"),react=e.target.closest("[data-club-react]");if(tab)return show(tab.dataset.clubTab);if(mission)return navigateTo(mission.dataset.missionView);if(route)return navigateTo(route.dataset.route);if(e.target.closest("[data-club-community]"))return navigateTo("community");if(song)return openSongDetail(Number(song.dataset.song));if(react){await api("rpc/set_song_reaction",{method:"POST",body:JSON.stringify({p_song_id:Number(react.dataset.songId),p_reaction:react.dataset.clubReact})});await detailReactions(Number(react.dataset.songId));showStatus(t("done"));}}
const oldOpen=openSongDetail;openSongDetail=function(id){record("listen",Number(id));oldOpen(id);setTimeout(()=>detailReactions(Number(id)),80)};
const oldFavorite=window.toggleFavorite;window.toggleFavorite=async function(id){const adding=!favoriteSongIds.has(Number(id));await oldFavorite(id);if(adding&&favoriteSongIds.has(Number(id)))await record("favorite",Number(id))};
const oldRecommend=window.submitRecommendation;window.submitRecommendation=async function(id,recommended){await oldRecommend(id,recommended);if(recommended)await record("recommend",Number(id))};
const oldRating=window.submitRating;window.submitRating=async function(id,...args){await oldRating(id,...args);await record("rate",Number(id))};
const oldRender=renderView;renderView=function(view,o={}){oldRender(view,o);document.querySelector("[data-club-route]")?.classList.toggle("is-active",view==="club");if(view==="club")hub();if(view==="detail")setTimeout(()=>detailReactions(Number(new URLSearchParams(location.search).get("song"))),100)};
const oldLang=setInterfaceLanguage;setInterfaceLanguage=function(l,p=true){oldLang(l,p);localize();if(currentView==="club")hub()};
document.addEventListener("DOMContentLoaded",install);
})();
