(()=>{
"use strict";
const LANGS=['ja','en','ko','zh','ru','es','fr'];
const REGIONS=[['JP','Japan'],['EA','East Asia'],['NA','North America'],['SE','Southeast Asia'],['ME','Middle East'],['EU','Europe'],['LA','Latin America'],['SA','South Asia'],['AF','Africa'],['OC','Oceania']];
const COPY={
 ja:{nav:'世界へ',title:'J-POPを世界へ。',lead:'発見、翻訳、共有をひとつにつないで、まだ知られていない曲を世界へ届けよう。',quiz:'30秒診断',region:'世界の発見',translate:'翻訳に参加',playlist:'外部で聴く',share:'シェアカード',invite:'アンバサダー',trust:'信頼性',metrics:'成長状況',start:'診断を始める',next:'次へ',copy:'リンクをコピー',download:'画像を保存',submit:'提案を送る'},
 en:{nav:'Global',title:'Take J-pop worldwide.',lead:'Turn discovery, translation and sharing into one global music movement.',quiz:'30-sec taste quiz',region:'Regional discoveries',translate:'Community translation',playlist:'Listen elsewhere',share:'Share cards',invite:'Ambassadors',trust:'Trust & safety',metrics:'Growth pulse',start:'Start the quiz',next:'Next',copy:'Copy link',download:'Save image',submit:'Send proposal'},
 ko:{nav:'글로벌',title:'J-pop을 세계로.',lead:'발견, 번역, 공유를 하나의 글로벌 음악 커뮤니티로 연결합니다.',quiz:'30초 취향 테스트',region:'지역별 발견',translate:'커뮤니티 번역',playlist:'다른 서비스에서 듣기',share:'공유 카드',invite:'앰배서더',trust:'신뢰와 안전',metrics:'성장 현황',start:'테스트 시작',next:'다음',copy:'링크 복사',download:'이미지 저장',submit:'제안 보내기'},
 zh:{nav:'全球',title:'让J-pop走向世界。',lead:'把发现、翻译与分享连接成全球音乐社区。',quiz:'30秒品味测试',region:'地区发现',translate:'社区翻译',playlist:'在其他平台收听',share:'分享卡片',invite:'推广大使',trust:'信任与安全',metrics:'增长数据',start:'开始测试',next:'下一步',copy:'复制链接',download:'保存图片',submit:'提交建议'},
 ru:{nav:'Мир',title:'J-pop для всего мира.',lead:'Объединяем открытия, переводы и обмен музыкой.',quiz:'Тест за 30 секунд',region:'Находки по регионам',translate:'Переводы сообщества',playlist:'Слушать на сервисах',share:'Карточки',invite:'Амбассадоры',trust:'Доверие',metrics:'Рост',start:'Начать тест',next:'Далее',copy:'Копировать ссылку',download:'Сохранить',submit:'Отправить'},
 es:{nav:'Global',title:'J-pop para todo el mundo.',lead:'Unimos descubrimiento, traducción y comunidad musical.',quiz:'Test de 30 segundos',region:'Hallazgos regionales',translate:'Traducción comunitaria',playlist:'Escuchar fuera',share:'Tarjetas para compartir',invite:'Embajadores',trust:'Confianza',metrics:'Crecimiento',start:'Empezar',next:'Siguiente',copy:'Copiar enlace',download:'Guardar imagen',submit:'Enviar propuesta'},
 fr:{nav:'Monde',title:'Le J-pop au monde entier.',lead:'Découverte, traduction et partage réunis dans une communauté mondiale.',quiz:'Test en 30 secondes',region:'Découvertes régionales',translate:'Traduction participative',playlist:'Écouter ailleurs',share:'Cartes à partager',invite:'Ambassadeurs',trust:'Confiance',metrics:'Croissance',start:'Commencer',next:'Suivant',copy:'Copier le lien',download:'Enregistrer',submit:'Envoyer'}
};
const q=s=>document.querySelector(s), esc=v=>escapeHtml(String(v??'')), tr=k=>(COPY[interfaceLanguage]||COPY.en)[k]||COPY.en[k]||k;
const g=(en,ja)=>interfaceLanguage==='ja'?ja:en;
const incomingReferral=new URLSearchParams(location.search).get('ref');
const state={tab:'quiz',quizStep:0,answers:[],region:'',metrics:[],localizations:new Map(),shareSong:null};
const SESSION=localStorage.getItem('jhg_growth_session')||crypto.randomUUID();localStorage.setItem('jhg_growth_session',SESSION);
VALID_VIEWS.add('global');

function activeSong(){const id=Number(new URLSearchParams(location.search).get('song'));return songs.find(s=>Number(s.id)===id)||songs[0];}
function updateSeo(){
 const lang=LANGS.includes(interfaceLanguage)?interfaceLanguage:'en',u=new URL(location.href);u.searchParams.set('lang',lang);u.searchParams.delete('ref');history.replaceState(history.state,'',u);
 document.documentElement.lang=lang;
 let title='Japan Hidden Gems — Discover overlooked J-pop';
 const s=activeSong();if(['detail','listen'].includes(currentView)&&s)title=`${songTitle(s)} — ${songArtist(s)} | Japan Hidden Gems`;
 else if(currentView==='ranking')title='Hidden Gem J-pop Ranking | Japan Hidden Gems';else if(currentView==='global')title=`${tr('title')} | Japan Hidden Gems`;
 document.title=title;
 const desc=tr('lead');q('meta[name="description"]')?.setAttribute('content',desc);
 q('meta[property="og:title"]')?.setAttribute('content',title);q('meta[property="og:description"]')?.setAttribute('content',desc);q('meta[property="og:url"]')?.setAttribute('content',u.href);
 q('link[rel="canonical"]')?.remove();document.head.insertAdjacentHTML('beforeend',`<link rel="canonical" href="${esc(location.origin+location.pathname+u.search)}">`);
 document.querySelectorAll('link[rel="alternate"][hreflang]').forEach(n=>n.remove());
 LANGS.forEach(l=>{const x=new URL(u);x.searchParams.set('lang',l);document.head.insertAdjacentHTML('beforeend',`<link rel="alternate" hreflang="${l}" href="${esc(x.href)}">`)});
 const old=q('#jhgStructuredData');old?.remove();const data={"@context":"https://schema.org","@type":s&&['detail','listen'].includes(currentView)?'MusicRecording':'WebSite',name:s&&['detail','listen'].includes(currentView)?songTitle(s):'Japan Hidden Gems',url:u.href,inLanguage:lang,description:desc};
 const script=document.createElement('script');script.id='jhgStructuredData';script.type='application/ld+json';script.textContent=JSON.stringify(data);document.head.append(script);
}
async function track(name,metadata={}){if(!currentUser?.id)return;const body={user_id:currentUser.id,session_id:SESSION,event_name:name,locale:interfaceLanguage||'en',region_code:listenerProfile?.country_code||null,page_view:currentView,metadata};rest('growth_events',{method:'POST',authenticated:true,headers:{Prefer:'return=minimal'},body:JSON.stringify(body)}).catch(()=>{});}
function install(){
 const nav=q('.primary-nav'),lang=q('.language-control');if(nav&&!q('[data-global-route]')){const b=document.createElement('button');b.className='nav-item';b.type='button';b.dataset.globalRoute='global';b.textContent=tr('nav');b.onclick=()=>navigateTo('global');nav.insertBefore(b,lang)}
 q('main')?.insertAdjacentHTML('beforeend',`<section class="shell section screen-panel global-screen" data-screen="global"><div class="global-hero"><div><p id="globalEyebrow" class="eyebrow dark"></p><h2 id="globalTitle"></h2><p id="globalLead" class="section-copy"></p></div><p id="globalCatalogSummary" class="global-muted"></p></div><div id="globalTabs" class="global-tabs"></div><div id="globalArea" class="global-panel"></div></section>`);
 q('footer .footer-inner')?.insertAdjacentHTML('beforeend',`<p id="globalFooterLinks"><a href="privacy.html">${g('Privacy','プライバシー')}</a> · <a href="community-guidelines.html">${g('Community guidelines','コミュニティ指針')}</a> · <a href="embed.html">${g('Embed JHG','JHGを埋め込む')}</a></p>`);
 document.addEventListener('click',click);document.addEventListener('submit',submit);localize();setTimeout(startup,1200);
}
async function startup(){if(!currentUser?.id)return setTimeout(startup,800);await loadLocalizations();if(incomingReferral)rest('rpc/claim_referral',{method:'POST',authenticated:true,body:JSON.stringify({p_code:incomingReferral,p_event_type:'visit'})}).catch(()=>{});track('session_start');updateSeo();}
async function loadLocalizations(){const rows=await rest('song_localizations?select=song_id,locale,localized_title,localized_artist,cultural_note').catch(()=>[]);state.localizations=new Map(rows.map(r=>[`${r.song_id}:${r.locale}`,r]));}
function localize(){q('[data-global-route]')&&(q('[data-global-route]').textContent=tr('nav'));q('#globalTitle')&&(q('#globalTitle').textContent=tr('title'));q('#globalLead')&&(q('#globalLead').textContent=tr('lead'));q('#globalEyebrow')&&(q('#globalEyebrow').textContent=g('JHG WORLDWIDE','JHG 世界プロジェクト'));q('#globalCatalogSummary')&&(q('#globalCatalogSummary').textContent=g('7 languages · 10 regions · one shared catalog','7言語・10地域・ひとつの共通カタログ'));q('#globalFooterLinks')&&(q('#globalFooterLinks').innerHTML=`<a href="privacy.html">${g('Privacy','プライバシー')}</a> · <a href="community-guidelines.html">${g('Community guidelines','コミュニティ指針')}</a> · <a href="embed.html">${g('Embed JHG','JHGを埋め込む')}</a>`);tabs();updateSeo();}
const tabsList=['quiz','region','translate','playlist','share','invite','trust','metrics'];
function tabs(){const e=q('#globalTabs');if(e)e.innerHTML=tabsList.map(k=>`<button data-global-tab="${k}" class="${state.tab===k?'is-active':''}">${esc(tr(k))}</button>`).join('')}
async function hub(){tabs();await render(state.tab);track('global_hub_view')}
async function render(tab){state.tab=tab;tabs();const a=q('#globalArea');if(!a)return;a.innerHTML=`<p class="muted">${g('Loading…','読み込み中…')}</p>`;try{await ({quiz,region,translate,playlist,share,invite,trust,metrics}[tab]||quiz)(a)}catch(e){a.innerHTML=`<p class="form-error">${esc(e.message)}</p>`}}

const QUESTIONS_EN=[
 ['When do you listen?',['Late night','Morning','Travel','Anytime']],['Choose an energy',['Calm','Emotional','Energetic','Experimental']],['Pick an era',['1980s','1990s','2000s','2010s+']],['What matters most?',['Melody','Lyrics & story','Voice','Production']],['Choose a scene',['City pop','Rock band','Vocaloid','Idol pop']]
];
const QUESTIONS_JA=[
 ['いつ聴くことが多い？',['深夜','朝','移動中','いつでも']],['好きなエネルギー感は？',['穏やか','感情的','エネルギッシュ','実験的']],['好きな年代は？',['1980年代','1990年代','2000年代','2010年代以降']],['曲で最も大切なのは？',['メロディー','歌詞と物語','歌声','サウンド制作']],['好きなシーンは？',['シティポップ','ロックバンド','ボカロ','アイドルポップ']]
];
function quiz(a){const questions=interfaceLanguage==='ja'?QUESTIONS_JA:QUESTIONS_EN;if(state.quizStep>=questions.length)return quizResult(a);const [question,opts]=questions[state.quizStep];a.innerHTML=`<p class="eyebrow dark">${tr('quiz')}</p><h3>${esc(question)}</h3><div class="quiz-progress"><span style="width:${state.quizStep/questions.length*100}%"></span></div><div class="quiz-options">${opts.map((o,i)=>`<button data-quiz-answer="${i}">${esc(o)}</button>`).join('')}</div><p class="global-muted">${state.quizStep+1} / ${questions.length}</p>`}
function quizResult(a){const score=state.answers.reduce((x,y)=>x+y,0),types=interfaceLanguage==='ja'?['真夜中のシティ探検家','心揺さぶる物語探し','刺激的なJ-POP冒険家','懐かしの名曲ハンター']:['Midnight City Explorer','Emotional Story Seeker','Electric J-pop Adventurer','Retro Hidden-Gem Hunter'],type=types[score%types.length],pool=[...songs].filter(s=>!s.is_hidden).sort((x,y)=>((x.id+score)%11)-((y.id+score)%11)).slice(0,5);a.innerHTML=`<div class="taste-result"><div class="taste-badge">${esc(type)}</div><div><p class="eyebrow dark">${g('YOUR J-POP TYPE','あなたのJ-POPタイプ')}</p><h3>${esc(type)}</h3><p>${g('Your five-song starting point is ready.','あなたに合う最初の5曲を選びました。')}</p><div class="global-actions"><button class="button" data-generate-card="taste">${tr('share')}</button><button class="button button-ghost" data-quiz-reset>${g('Retry','もう一度')}</button></div></div></div><div class="global-grid">${pool.map(songCard).join('')}</div>`;track('taste_quiz_complete',{type});if(incomingReferral)rest('rpc/claim_referral',{method:'POST',authenticated:true,body:JSON.stringify({p_code:incomingReferral,p_event_type:'activated'})}).catch(()=>{})}
function localized(s){return state.localizations.get(`${s.id}:${interfaceLanguage}`)}
function displayTitle(s){return localized(s)?.localized_title||songTitle(s)}function displayArtist(s){return localized(s)?.localized_artist||songArtist(s)}
function songCard(s){return `<article class="global-card">${songArtwork(s,'global-cover')}<strong>${esc(displayTitle(s))}</strong><small>${esc(displayArtist(s))}${s.year?` · ${s.year}`:''}</small><button class="action" data-global-song="${s.id}">${g('Open','開く')}</button></article>`}
async function region(a){a.innerHTML=`<p class="eyebrow dark">${tr('region')}</p><h3>${g('What is your region discovering?','あなたの地域で発見されている曲')}</h3><div class="region-picker"><select id="globalRegion" class="select"><option value="">${g('All regions','すべての地域')}</option>${REGIONS.map(([v,n])=>`<option value="${v}" ${state.region===v?'selected':''}>${esc(regionName(v,n))}</option>`).join('')}</select></div><div id="regionSongs" class="global-grid"></div>`;await loadRegion()}
function regionName(code,fallback){const ja={JP:'日本',EA:'東アジア',NA:'北アメリカ',SE:'東南アジア',ME:'中東',EU:'ヨーロッパ',LA:'ラテンアメリカ',SA:'南アジア',AF:'アフリカ',OC:'オセアニア'};return interfaceLanguage==='ja'?ja[code]:fallback}
async function loadRegion(){const rows=await rest('rpc/get_region_discoveries',{method:'POST',authenticated:true,body:JSON.stringify({p_region:state.region||null,p_limit:18})}).catch(()=>[]),e=q('#regionSongs');if(e)e.innerHTML=rows.map(r=>{const s=songs.find(x=>Number(x.id)===Number(r.song_id));return s?songCard(s).replace('</article>',`<small>${Number(r.listeners)} ${g('listeners','人が発見')} · ${Number(r.activity_score).toFixed(0)} ${g('pts','ポイント')}</small></article>`):''}).join('')||`<p class="muted">${g('More listener activity is needed here.','この地域は、もう少し回答が集まると表示されます。')}</p>`;track('region_hub_view',{region:state.region||'all'})}
async function translate(a){const s=activeSong();if(!s){a.innerHTML=`<p>${g('No songs available.','表示できる曲がありません。')}</p>`;return}a.innerHTML=`<p class="eyebrow dark">${tr('translate')}</p><h3>${g('Help listeners understand a song','曲の魅力を海外の人へ伝えよう')}</h3><form id="translationForm" class="translation-form"><select name="song" class="select">${songs.slice(0,500).map(x=>`<option value="${x.id}" ${x.id===s.id?'selected':''}>${esc(songTitle(x))} — ${esc(songArtist(x))}</option>`).join('')}</select><select name="locale" class="select">${LANGS.filter(l=>l!=='ja').map(l=>`<option value="${l}" ${l===interfaceLanguage?'selected':''}>${l.toUpperCase()}</option>`).join('')}</select><input class="text-input" name="title" maxlength="240" placeholder="${g('Localized or romanized title','翻訳名またはローマ字の曲名')}" required><input class="text-input" name="artist" maxlength="200" placeholder="${g('Localized artist name','翻訳名またはローマ字のアーティスト名')}" required><textarea name="note" maxlength="1200" placeholder="${g('Cultural context (no lyrics)','文化的な背景や解説（歌詞は入力しないでください）')}"></textarea><button class="button">${tr('submit')}</button></form><div id="translationRows"></div>`;await proposals(s.id,interfaceLanguage==='ja'?'en':interfaceLanguage)}
async function proposals(songId,locale){const rows=await rest('rpc/get_translation_proposals',{method:'POST',authenticated:true,body:JSON.stringify({p_song_id:Number(songId),p_locale:locale})}).catch(()=>[]);q('#translationRows')&&(q('#translationRows').innerHTML=rows.map(r=>`<article class="translation-row"><div><strong>${esc(r.proposed_title)}</strong><small>${esc(r.proposed_artist)}</small><p>${esc(r.cultural_note)}</p></div><div class="translation-votes"><button data-translation-vote="${r.id}" data-vote="1">▲</button><b>${r.score}</b><button data-translation-vote="${r.id}" data-vote="-1">▼</button></div></article>`).join('')||`<p class="muted">${g('Be the first to suggest a translation.','最初の翻訳案を投稿してみましょう。')}</p>`)}
function selectedSongs(){const fav=songs.filter(s=>favoriteSongIds.has(Number(s.id)));return (fav.length?fav:songs).filter(s=>s.youtube_video_id).slice(0,40)}
function playlist(a){const list=selectedSongs(),ids=list.map(s=>s.youtube_video_id).join(',');a.innerHTML=`<p class="eyebrow dark">${tr('playlist')}</p><h3>${g('Take your discoveries with you','見つけた曲を、いつものサービスで聴こう')}</h3><p>${g(`${list.length} songs from ${favoriteSongIds.size?'your favorites':'JHG'}.`,`${favoriteSongIds.size?'お気に入り':'JHG'}から${list.length}曲を選びました。`)}</p><div class="playlist-tools"><a class="button" target="_blank" rel="noopener" href="https://www.youtube.com/watch_videos?video_ids=${encodeURIComponent(ids)}">${g('Play on YouTube','YouTubeで再生')}</a><a class="button button-ghost" target="_blank" rel="noopener" href="https://open.spotify.com/search/${encodeURIComponent(list[0]?displayTitle(list[0])+' '+displayArtist(list[0]):'J-pop')}">${g('Search on Spotify','Spotifyで検索')}</a><a class="button button-ghost" target="_blank" rel="noopener" href="https://music.apple.com/us/search?term=${encodeURIComponent(list[0]?displayTitle(list[0])+' '+displayArtist(list[0]):'J-pop')}">${g('Search on Apple Music','Apple Musicで検索')}</a><button class="button button-ghost" data-copy-tracklist>${tr('copy')}</button></div><div class="global-grid">${list.slice(0,9).map(songCard).join('')}</div>`}
function share(a){const list=selectedSongs().slice(0,5);a.innerHTML=`<p class="eyebrow dark">${tr('share')}</p><h3>${g('Share your hidden-gem five','あなたの隠れた名曲5選を共有')}</h3><p>${g('Create a copyright-safe card containing titles, artists and a link—no audio or lyrics.','曲名・アーティスト名・リンクだけを使った、著作権に配慮したカードを作成します。')}</p><div class="global-actions"><button class="button" data-generate-card="top5">${g('Generate card','カードを作成')}</button><button class="button button-ghost" data-share-url>${tr('copy')}</button></div><canvas id="shareCanvas" class="share-preview" width="1080" height="1350" aria-label="${g('Share card preview','共有カードのプレビュー')}"></canvas>`;drawCard(list,g('MY J-POP HIDDEN GEMS','私のJ-POP隠れた名曲'))}
function drawCard(list,heading){const c=q('#shareCanvas');if(!c)return;const x=c.getContext('2d');x.fillStyle='#f6efe5';x.fillRect(0,0,c.width,c.height);x.fillStyle='#d94b2b';x.fillRect(0,0,36,c.height);x.fillStyle='#171513';x.font='900 42px system-ui';x.fillText('JAPAN HIDDEN GEMS',90,105);x.font='800 72px Georgia';wrap(x,heading,90,210,900,82);x.font='700 38px system-ui';list.forEach((s,i)=>{x.fillStyle='#d94b2b';x.fillText(String(i+1).padStart(2,'0'),90,440+i*145);x.fillStyle='#171513';x.fillText(displayTitle(s).slice(0,34),180,440+i*145);x.fillStyle='#756e65';x.font='32px system-ui';x.fillText(displayArtist(s).slice(0,42),180,485+i*145);x.font='700 38px system-ui'});x.fillStyle='#171513';x.font='28px system-ui';x.fillText(location.host,90,1260)}
function wrap(x,t,px,py,w,h){let line='';String(t).split(' ').forEach(word=>{const test=line+word+' ';if(x.measureText(test).width>w){x.fillText(line,px,py);line=word+' ';py+=h}else line=test});x.fillText(line,px,py)}
async function invite(a){const code=await rest('rpc/ensure_referral_code',{method:'POST',authenticated:true,body:'{}'}),rows=await rest('rpc/get_my_referral_summary',{method:'POST',authenticated:true,body:'{}'}).catch(()=>[]),r=rows[0]||{code,visits:0,activations:0,shares:0},url=new URL(location.origin+location.pathname);url.searchParams.set('ref',r.code||code);a.innerHTML=`<p class="eyebrow dark">${tr('invite')}</p><h3>${g('Help J-pop cross borders','J-POPが国境を越えるきっかけを作ろう')}</h3><p>${g('Earn community recognition by bringing listeners who actually discover and rate music. No cash rewards.','新しい曲を発見・評価してくれるリスナーを招待すると、コミュニティでの活動実績として記録されます。金銭報酬はありません。')}</p><div class="referral-box"><input id="referralUrl" class="text-input" readonly value="${esc(url.href)}"><button class="button" data-copy-referral>${tr('copy')}</button></div><div class="metric-grid"><article class="metric-card"><strong>${r.visits||0}</strong><span>${g('Visits','訪問')}</span></article><article class="metric-card"><strong>${r.activations||0}</strong><span>${g('Activated','参加開始')}</span></article><article class="metric-card"><strong>${r.shares||0}</strong><span>${g('Shares','共有')}</span></article></div>`}
function trust(a){a.innerHTML=`<p class="eyebrow dark">${tr('trust')}</p><h3>${g('Discovery people can trust','安心して曲を発見できる仕組み')}</h3><div class="trust-list"><article><strong>${g('Real and reference data are separated','実データと参考データを分離')}</strong><p>${g('Starter values are clearly labeled and never presented as real listener reviews.','初期の参考値には明確な表示を付け、実際の利用者評価として扱いません。')}</p></article><article><strong>${g('Transparent ranking','透明なランキング')}</strong><p>${g('GEMS methodology and minimum sample thresholds remain visible.','GEMS値の計算方法と最低回答数を公開します。')}</p></article><article><strong>${g('Copyright-aware','著作権への配慮')}</strong><p>${g('JHG embeds official services and does not republish full lyrics or audio.','公式サービスを埋め込み、歌詞全文や音源を転載しません。')}</p></article><article><strong>${g('Community corrections','利用者による訂正')}</strong><p>${g('Users can report metadata and propose translations; administrators review changes.','曲情報の報告や翻訳提案を受け付け、管理者が確認します。')}</p></article><article><strong>${g('Privacy by design','プライバシーを守る設計')}</strong><p>${g('Only broad region and age bands are collected for public aggregates.','公開集計には大まかな地域と年齢層だけを使用します。')}</p></article><article><strong>${g('Moderation','投稿の管理')}</strong><p>${g('Spam, impersonation and abusive contributions can be reported and removed.','迷惑投稿やなりすまし、不適切な投稿は報告・削除できます。')}</p></article></div>`}
async function metrics(a){const rows=await rest('rpc/get_global_growth_metrics',{method:'POST',authenticated:true,body:'{"p_days":30}'}).catch(()=>[]);state.metrics=rows;const event=Object.fromEntries(rows.filter(r=>r.metric==='event').map(r=>[r.dimension,Number(r.value)]));const catalog=rows.find(r=>r.metric==='catalog')?.value||0,curators=rows.find(r=>r.dimension==='public_curators')?.value||0;a.innerHTML=`<p class="eyebrow dark">${tr('metrics')}</p><h3>${g('Last 30 days','直近30日')}</h3><div class="metric-grid"><article class="metric-card"><strong>${catalog}</strong><span>${g('Visible songs','公開曲')}</span></article><article class="metric-card"><strong>${event.session_start||0}</strong><span>${g('Sessions','利用回数')}</span></article><article class="metric-card"><strong>${event.taste_quiz_complete||0}</strong><span>${g('Quiz finishes','診断完了')}</span></article><article class="metric-card"><strong>${event.share_complete||0}</strong><span>${g('Shares','共有')}</span></article><article class="metric-card"><strong>${curators}</strong><span>${g('Curators','キュレーター')}</span></article></div><h3>${g('Languages','言語')}</h3><div class="global-grid">${rows.filter(r=>r.metric==='locale').map(r=>`<article class="global-card"><strong>${r.dimension.toUpperCase()}</strong><small>${r.value} ${g('events','件')}</small></article>`).join('')||`<p class="muted">${g('Data starts collecting now.','データの集計を開始したばかりです。')}</p>`}</div>`}

async function click(e){const tab=e.target.closest('[data-global-tab]');if(tab)return render(tab.dataset.globalTab);const ans=e.target.closest('[data-quiz-answer]');if(ans){state.answers.push(Number(ans.dataset.quizAnswer));state.quizStep++;return render('quiz')}if(e.target.closest('[data-quiz-reset]')){state.quizStep=0;state.answers=[];return render('quiz')}const song=e.target.closest('[data-global-song]');if(song)return openSongDetail(Number(song.dataset.globalSong));const vote=e.target.closest('[data-translation-vote]');if(vote){await rest('song_localization_votes?on_conflict=proposal_id,user_id',{method:'POST',authenticated:true,headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({proposal_id:Number(vote.dataset.translationVote),user_id:currentUser.id,vote:Number(vote.dataset.vote)})});const f=q('#translationForm'),d=new FormData(f);return proposals(d.get('song'),d.get('locale'))}if(e.target.closest('[data-copy-tracklist]')){await navigator.clipboard.writeText(selectedSongs().map((s,i)=>`${i+1}. ${displayTitle(s)} — ${displayArtist(s)}`).join('\n'));track('playlist_export');return showStatus(g('Track list copied.','曲目リストをコピーしました。'))}if(e.target.closest('[data-share-url]')){await navigator.clipboard.writeText(location.href);track('share_complete',{type:'url'});return showStatus(g('Link copied.','リンクをコピーしました。'))}if(e.target.closest('[data-copy-referral]')){await navigator.clipboard.writeText(q('#referralUrl').value);track('referral_shared');track('share_complete',{type:'referral'});return showStatus(g('Invite link copied.','招待リンクをコピーしました。'))}if(e.target.closest('[data-generate-card]')){const c=q('#shareCanvas');if(c){const a=document.createElement('a');a.download='jhg-hidden-gems.png';a.href=c.toDataURL('image/png');a.click();track('share_complete',{type:'card'})}else{state.tab='share';await render('share')}}}
async function submit(e){if(e.target.id!=='translationForm')return;e.preventDefault();const d=new FormData(e.target);await rest('song_localization_proposals',{method:'POST',authenticated:true,body:JSON.stringify({song_id:Number(d.get('song')),user_id:currentUser.id,locale:d.get('locale'),proposed_title:d.get('title'),proposed_artist:d.get('artist'),cultural_note:d.get('note')})});track('translation_proposed',{locale:d.get('locale')});showStatus(g('Translation proposal received.','翻訳案を受け付けました。'));e.target.reset();await proposals(d.get('song'),d.get('locale'))}
document.addEventListener('change',e=>{if(e.target.id==='globalRegion'){state.region=e.target.value;loadRegion()}if(e.target.closest('#translationForm')&&['song','locale'].includes(e.target.name)){const d=new FormData(e.target.form);proposals(d.get('song'),d.get('locale'))}});
const oldRender=renderView;renderView=function(view,o={}){oldRender(view,o);q('[data-global-route]')?.classList.toggle('is-active',view==='global');updateSeo();track('page_view',{view});if(view==='global')hub()};
const oldLang=setInterfaceLanguage;setInterfaceLanguage=function(l,p=true){oldLang(l,p);localize();if(currentView==='global')render(state.tab)};
document.addEventListener('DOMContentLoaded',install);
})();
