/* Japan Hidden Gems — retention, sharing, trust and data-quality layer */
(function () {
  "use strict";

  const GROWTH_LANG = {
    ja:{daily:"今日の5曲",profile:"音楽プロフィール",dailyTitle:"今日のJ-POP発見",dailyCopy:"5曲を聴いて、最後に今日いちばんの発見を選ぼう。",start:"今日の5曲を始める",known:"知っていた",newSong:"知らなかった",rate:"聴いた後の評価",next:"保存して次へ",discovery:"今日の発見曲を選ぶ",complete:"今日のチャレンジ完了！",share:"結果をシェア",download:"画像を保存",profileTitle:"あなたの音楽プロフィール",profileCopy:"回答・お気に入り・大会結果から、好みをまとめました。",discovered:"発見した曲",rated:"評価した曲",cups:"J-POP杯優勝曲",topTags:"好きなタグ",eras:"好きな年代",trustRef:"参考データ",trustCollecting:"集計中",trustReal:"実データ",confidence:"信頼度",low:"低",medium:"中",high:"高",realOnly:"参考データを除外",report:"問題を報告",reportSent:"報告を受け付けました。",size:"大会規模",four:"4曲",eight:"8曲",sixteen:"16曲",shareCup:"優勝結果をシェア"},
    en:{daily:"Daily 5",profile:"Music Profile",dailyTitle:"Today's J-pop discovery",dailyCopy:"Explore five songs, then choose your discovery of the day.",start:"Start today's five",known:"Knew it",newSong:"New to me",rate:"Rating after listening",next:"Save & next",discovery:"Choose today's discovery",complete:"Daily challenge complete!",share:"Share result",download:"Save image",profileTitle:"Your music profile",profileCopy:"Built from your ratings, favorites and Cup results.",discovered:"Songs discovered",rated:"Songs rated",cups:"J-POP Cup champions",topTags:"Favorite tags",eras:"Favorite eras",trustRef:"Reference data",trustCollecting:"Collecting",trustReal:"Real data",confidence:"Confidence",low:"Low",medium:"Medium",high:"High",realOnly:"Hide reference data",report:"Report a problem",reportSent:"Report received.",size:"Tournament size",four:"4 songs",eight:"8 songs",sixteen:"16 songs",shareCup:"Share champion"},
    ko:{daily:"오늘의 5곡",profile:"음악 프로필",dailyTitle:"오늘의 J-POP 발견",dailyCopy:"5곡을 듣고 오늘의 발견곡을 고르세요.",start:"오늘의 5곡 시작",known:"알고 있었음",newSong:"처음 들음",rate:"감상 후 평점",next:"저장 후 다음",discovery:"오늘의 발견곡 선택",complete:"오늘의 챌린지 완료!",share:"결과 공유",download:"이미지 저장",profileTitle:"나의 음악 프로필",profileCopy:"평가·즐겨찾기·컵 결과로 만들었습니다.",discovered:"발견한 곡",rated:"평가한 곡",cups:"컵 우승곡",topTags:"선호 태그",eras:"선호 시대",trustRef:"참고 데이터",trustCollecting:"집계 중",trustReal:"실제 데이터",confidence:"신뢰도",low:"낮음",medium:"보통",high:"높음",realOnly:"참고 데이터 숨기기",report:"문제 신고",reportSent:"신고가 접수되었습니다.",size:"대회 규모",four:"4곡",eight:"8곡",sixteen:"16곡",shareCup:"우승곡 공유"},
    zh:{daily:"今日5首",profile:"音乐档案",dailyTitle:"今日J-POP发现",dailyCopy:"试听5首歌曲，选出今天最喜欢的新发现。",start:"开始今日5首",known:"听过",newSong:"第一次听",rate:"试听后评分",next:"保存并继续",discovery:"选择今日发现",complete:"今日挑战完成！",share:"分享结果",download:"保存图片",profileTitle:"你的音乐档案",profileCopy:"根据评分、收藏和杯赛结果生成。",discovered:"发现歌曲",rated:"已评分",cups:"杯赛冠军",topTags:"偏好标签",eras:"偏好年代",trustRef:"参考数据",trustCollecting:"统计中",trustReal:"真实数据",confidence:"可信度",low:"低",medium:"中",high:"高",realOnly:"隐藏参考数据",report:"报告问题",reportSent:"报告已收到。",size:"比赛规模",four:"4首",eight:"8首",sixteen:"16首",shareCup:"分享冠军"},
    ru:{daily:"5 треков дня",profile:"Музыкальный профиль",dailyTitle:"J-pop открытие дня",dailyCopy:"Послушайте пять песен и выберите открытие дня.",start:"Начать",known:"Знал(а)",newSong:"Новинка",rate:"Оценка",next:"Сохранить",discovery:"Выберите открытие",complete:"Готово!",share:"Поделиться",download:"Сохранить картинку",profileTitle:"Ваш музыкальный профиль",profileCopy:"По оценкам, избранному и турнирам.",discovered:"Открыто песен",rated:"Оценено",cups:"Победители",topTags:"Любимые теги",eras:"Любимые эпохи",trustRef:"Справочные данные",trustCollecting:"Сбор данных",trustReal:"Реальные данные",confidence:"Надёжность",low:"Низкая",medium:"Средняя",high:"Высокая",realOnly:"Скрыть справочные данные",report:"Сообщить о проблеме",reportSent:"Сообщение принято.",size:"Размер турнира",four:"4 песни",eight:"8 песен",sixteen:"16 песен",shareCup:"Поделиться победителем"},
    es:{daily:"5 de hoy",profile:"Perfil musical",dailyTitle:"Descubrimiento J-pop de hoy",dailyCopy:"Escucha cinco canciones y elige tu descubrimiento del día.",start:"Empezar",known:"Ya la conocía",newSong:"Nueva para mí",rate:"Valoración",next:"Guardar y seguir",discovery:"Elige tu descubrimiento",complete:"¡Reto completado!",share:"Compartir",download:"Guardar imagen",profileTitle:"Tu perfil musical",profileCopy:"Creado con tus valoraciones, favoritos y copas.",discovered:"Canciones descubiertas",rated:"Canciones valoradas",cups:"Campeonas",topTags:"Etiquetas favoritas",eras:"Épocas favoritas",trustRef:"Datos de referencia",trustCollecting:"Recopilando",trustReal:"Datos reales",confidence:"Confianza",low:"Baja",medium:"Media",high:"Alta",realOnly:"Ocultar datos de referencia",report:"Informar problema",reportSent:"Informe recibido.",size:"Tamaño",four:"4 canciones",eight:"8 canciones",sixteen:"16 canciones",shareCup:"Compartir campeona"},
    fr:{daily:"5 du jour",profile:"Profil musical",dailyTitle:"Découverte J-pop du jour",dailyCopy:"Écoutez cinq titres puis choisissez votre découverte du jour.",start:"Commencer",known:"Je connaissais",newSong:"Nouveau pour moi",rate:"Note après écoute",next:"Enregistrer",discovery:"Choisir la découverte",complete:"Défi terminé !",share:"Partager",download:"Enregistrer l’image",profileTitle:"Votre profil musical",profileCopy:"Créé à partir de vos notes, favoris et coupes.",discovered:"Titres découverts",rated:"Titres notés",cups:"Vainqueurs",topTags:"Tags préférés",eras:"Époques préférées",trustRef:"Données de référence",trustCollecting:"Collecte en cours",trustReal:"Données réelles",confidence:"Fiabilité",low:"Faible",medium:"Moyenne",high:"Élevée",realOnly:"Masquer les références",report:"Signaler un problème",reportSent:"Signalement reçu.",size:"Taille du tournoi",four:"4 titres",eight:"8 titres",sixteen:"16 titres",shareCup:"Partager le vainqueur"}
  };
  const t=(key)=>(GROWTH_LANG[interfaceLanguage]||GROWTH_LANG.en)[key]||GROWTH_LANG.en[key]||key;
  let dailyState=null;

  function navButton(route,key){const b=document.createElement("button");b.type="button";b.className="nav-item growth-nav";b.dataset.growthRoute=route;b.textContent=t(key);b.addEventListener("click",()=>navigateTo(route));return b;}
  function install(){
    VALID_VIEWS.add("daily"); VALID_VIEWS.add("profile");
    const nav=document.querySelector(".primary-nav"),lang=document.querySelector(".language-control");
    if(nav&&!nav.querySelector('[data-growth-route="daily"]')){nav.insertBefore(navButton("daily","daily"),lang);nav.insertBefore(navButton("profile","profile"),lang);}
    document.querySelector("main")?.insertAdjacentHTML("beforeend",`<section class="shell section screen-panel growth-screen" data-screen="daily"><p class="eyebrow dark">DAILY DISCOVERY</p><h2 id="dailyTitle"></h2><p id="dailyCopy" class="section-copy"></p><div id="dailyArea"><button id="dailyStart" class="button action primary" type="button"></button></div><p id="dailyStatus" class="section-copy" aria-live="polite"></p></section><section class="shell section screen-panel growth-screen" data-screen="profile"><p class="eyebrow dark">LISTENING DNA</p><h2 id="growthProfileTitle"></h2><p id="growthProfileCopy" class="section-copy"></p><div id="growthProfileArea" class="profile-dashboard"><p class="muted">Loading…</p></div></section>`);
    document.querySelector("#dailyStart")?.addEventListener("click",startDaily);
    enhanceCup(); enhanceRanking(); installQualityReporting(); localize();
  }

  function localize(){
    document.querySelector('[data-growth-route="daily"]')&&(document.querySelector('[data-growth-route="daily"]').textContent=t("daily"));
    document.querySelector('[data-growth-route="profile"]')&&(document.querySelector('[data-growth-route="profile"]').textContent=t("profile"));
    [["dailyTitle","dailyTitle"],["dailyCopy","dailyCopy"],["dailyStart","start"],["growthProfileTitle","profileTitle"],["growthProfileCopy","profileCopy"]].forEach(([id,k])=>{const e=document.getElementById(id);if(e)e.textContent=t(k);});
    const sizeLabel=document.getElementById("cupSizeLabel");if(sizeLabel)sizeLabel.textContent=t("size");
    [["cupSize4","four"],["cupSize8","eight"],["cupSize16","sixteen"]].forEach(([id,k])=>{const e=document.getElementById(id);if(e)e.textContent=t(k);});
    const toggle=document.querySelector("#realDataOnlyLabel");if(toggle)toggle.textContent=t("realOnly");
  }

  async function startDaily(){
    const area=document.querySelector("#dailyArea"),status=document.querySelector("#dailyStatus");status.textContent="";
    try{
      const date=new Date().toISOString().slice(0,10);
      let sessions=await rest(`daily_discovery_sessions?select=id,song_ids,discovery_song_id,completed_at&user_id=eq.${currentUser.id}&challenge_date=eq.${date}`,{authenticated:true});
      let session=sessions?.[0];
      if(!session){
        const past=await rest(`daily_discovery_responses?select=song_id&user_id=eq.${currentUser.id}&order=created_at.desc&limit=250`,{authenticated:true});
        const seen=new Set((past||[]).map(x=>Number(x.song_id)));let pool=songs.filter(s=>s.youtube_url&&!seen.has(Number(s.id)));if(pool.length<5)pool=songs.filter(s=>s.youtube_url);
        const picks=shuffled(pool).slice(0,5);if(picks.length<5)throw new Error("Five playable songs are required.");
        const rows=await rest("daily_discovery_sessions?select=id,song_ids,discovery_song_id,completed_at",{method:"POST",authenticated:true,headers:{Prefer:"return=representation"},body:JSON.stringify({user_id:currentUser.id,challenge_date:date,song_ids:picks.map(s=>s.id)})});session=rows[0];
      }
      const answered=await rest(`daily_discovery_responses?select=song_id,heard_before,rating&session_id=eq.${session.id}`,{authenticated:true});
      dailyState={session,index:(answered||[]).length,songs:session.song_ids.map(id=>songs.find(s=>Number(s.id)===Number(id))).filter(Boolean),answered:answered||[]};renderDaily();
    }catch(e){status.textContent=e.message;}
  }

  function renderDaily(){
    const a=document.querySelector("#dailyArea");if(!dailyState)return;
    if(dailyState.session.completed_at||dailyState.index>=dailyState.songs.length){renderDailyChoice();return;}
    const s=dailyState.songs[dailyState.index];
    a.innerHTML=`<article class="daily-card">${songArtwork(s,"daily-artwork")}<p class="daily-progress">${dailyState.index+1}/5</p><h3>${escapeHtml(songTitle(s))}</h3><p class="meta">${escapeHtml(songArtist(s))}</p><div class="actions"><button class="action" onclick="window.openRating(${s.id})">${experienceText("listen")}</button></div><form id="dailyResponse"><fieldset><legend>${t("known")}</legend><label><input type="radio" name="heard" value="true" required> ${t("known")}</label><label><input type="radio" name="heard" value="false"> ${t("newSong")}</label></fieldset><label class="form-field"><span>${t("rate")}</span><select id="dailyRating" class="select" required><option value="">—</option>${[1,2,3,4,5].map(n=>`<option value="${n}">${n}/5</option>`).join("")}</select></label><button class="button action primary" type="submit">${t("next")}</button></form></article>`;
    document.querySelector("#dailyResponse").addEventListener("submit",saveDailyResponse);
  }
  async function saveDailyResponse(e){e.preventDefault();const s=dailyState.songs[dailyState.index],heard=e.target.elements.heard.value==="true",rating=Number(document.querySelector("#dailyRating").value);await rest("daily_discovery_responses",{method:"POST",authenticated:true,headers:{Prefer:"return=minimal"},body:JSON.stringify({session_id:dailyState.session.id,user_id:currentUser.id,song_id:s.id,heard_before:heard,rating})});if(audience==="japan"){await rest("recommendations?on_conflict=song_id,user_id",{method:"POST",authenticated:true,headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({song_id:s.id,user_id:currentUser.id,recommended:rating>=4,updated_at:new Date().toISOString()})});}else{await rest("ratings?on_conflict=song_id,user_id",{method:"POST",authenticated:true,headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({song_id:s.id,user_id:currentUser.id,heard_before:heard,rating,updated_at:new Date().toISOString()})});}dailyState.answered.push({song_id:s.id,heard_before:heard,rating});dailyState.index++;renderDaily();}
  function renderDailyChoice(){const a=document.querySelector("#dailyArea");if(dailyState.session.completed_at){const s=songs.find(x=>Number(x.id)===Number(dailyState.session.discovery_song_id));a.innerHTML=completeCard(s);return;}a.innerHTML=`<h3>${t("discovery")}</h3><div class="daily-choice-grid">${dailyState.songs.map(s=>`<button type="button" class="daily-choice" data-discovery="${s.id}">${songArtwork(s,"daily-choice-art")}<strong>${escapeHtml(songTitle(s))}</strong></button>`).join("")}</div>`;a.querySelectorAll("[data-discovery]").forEach(b=>b.addEventListener("click",()=>completeDaily(Number(b.dataset.discovery))));}
  async function completeDaily(id){await rest(`daily_discovery_sessions?id=eq.${dailyState.session.id}`,{method:"PATCH",authenticated:true,headers:{Prefer:"return=minimal"},body:JSON.stringify({discovery_song_id:id,completed_at:new Date().toISOString()})});dailyState.session.discovery_song_id=id;dailyState.session.completed_at=new Date().toISOString();renderDailyChoice();}
  function completeCard(s){return `<div class="daily-complete"><p class="eyebrow dark">${t("complete")}</p>${s?songArtwork(s,"daily-artwork"):""}<h3>${s?escapeHtml(songTitle(s)):""}</h3><div class="actions"><button class="action primary" type="button" id="shareDaily">${t("share")}</button><button class="action" type="button" id="downloadDaily">${t("download")}</button></div></div>`;}

  async function profile(){
    const area=document.querySelector("#growthProfileArea");
    try{const [dr,cups]=await Promise.all([rest(`daily_discovery_responses?select=song_id,heard_before,rating,created_at&user_id=eq.${currentUser.id}&order=created_at.desc&limit=500`,{authenticated:true}),rest(`tournament_runs?select=champion_song_id,completed_at&user_id=eq.${currentUser.id}&status=eq.completed&order=completed_at.desc&limit=50`,{authenticated:true})]);
      const rated=(dr||[]),discovered=rated.filter(x=>!x.heard_before).length,ids=new Set(rated.filter(x=>Number(x.rating)>=4).map(x=>Number(x.song_id))),fav=[...favoriteSongIds];fav.forEach(id=>ids.add(Number(id)));const liked=songs.filter(s=>ids.has(Number(s.id)));const tags=new Map(),eras=new Map();liked.forEach(s=>{(s.tags||[]).forEach(x=>tags.set(x.label_en,(tags.get(x.label_en)||0)+1));if(s.year){const e=Math.floor(Number(s.year)/10)*10+"s";eras.set(e,(eras.get(e)||0)+1);}});const top=m=>[...m].sort((a,b)=>b[1]-a[1]).slice(0,5);
      area.innerHTML=`<div class="profile-stat-grid"><article><strong>${discovered}</strong><span>${t("discovered")}</span></article><article><strong>${rated.length}</strong><span>${t("rated")}</span></article><article><strong>${cups.length}</strong><span>${t("cups")}</span></article></div><div class="profile-insights"><article><h3>${t("topTags")}</h3><p>${top(tags).map(x=>escapeHtml(x[0])).join(" · ")||"—"}</p></article><article><h3>${t("eras")}</h3><p>${top(eras).map(x=>escapeHtml(x[0])).join(" · ")||"—"}</p></article></div><div class="profile-champions">${(cups||[]).slice(0,6).map(c=>{const s=songs.find(x=>Number(x.id)===Number(c.champion_song_id));return s?`<article>${songArtwork(s,"profile-cover")}<strong>${escapeHtml(songTitle(s))}</strong></article>`:"";}).join("")}</div>`;
    }catch(e){area.innerHTML=`<p class="form-error">${escapeHtml(e.message)}</p>`;}
  }

  function enhanceCup(){const setup=document.querySelector(".cup-setup");if(!setup||document.querySelector("#cupSize"))return;setup.insertAdjacentHTML("beforeend",`<label class="filter-field"><span id="cupSizeLabel"></span><select id="cupSize" class="select"><option id="cupSize4" value="4"></option><option id="cupSize8" value="8" selected></option><option id="cupSize16" value="16"></option></select></label>`);const old=document.querySelector("#cupStart"),fresh=old.cloneNode(true);old.replaceWith(fresh);fresh.addEventListener("click",startSizedCup);const baseRender=renderCup;renderCup=function(){baseRender();const arena=document.querySelector("#cupArena");if(cupState?.champion&&arena&&!arena.querySelector("#shareCupChampion")){arena.querySelector(".actions")?.insertAdjacentHTML("beforeend",`<button id="shareCupChampion" class="action" type="button">${t("shareCup")}</button>`);if(!arena.querySelector(".actions"))arena.querySelector(".cup-champion")?.insertAdjacentHTML("beforeend",`<button id="shareCupChampion" class="action" type="button">${t("shareCup")}</button>`);}};}
  async function startSizedCup(){const size=Number(document.querySelector("#cupSize")?.value||8),mode=document.querySelector("#cupMode")?.value||"random",tagId=mode==="tag"?Number(document.querySelector("#cupTag")?.value):null;let eligible=[...songs];if(tagId)eligible=eligible.filter(s=>(s.tags||[]).some(tg=>Number(tg.id)===tagId));const status=document.querySelector("#cupStatus");if(eligible.length<size){status.textContent=`${size} playable songs are required.`;return;}const entrants=shuffled(eligible).slice(0,size);try{const rows=await rest("tournament_runs?select=id",{method:"POST",authenticated:true,headers:{Prefer:"return=representation"},body:JSON.stringify({user_id:currentUser.id,mode,tag_id:tagId,bracket_size:size,entrant_song_ids:entrants.map(s=>s.id)})});cupState={runId:rows[0].id,round:1,roundSongs:entrants,winners:[],matchIndex:0};status.textContent="";renderCup();}catch(e){status.textContent=e.message;}}

  function enhanceRanking(){const controls=document.querySelector(".ranking-controls");if(!controls||document.querySelector("#realDataOnly"))return;const l=document.createElement("label");l.className="real-data-toggle";l.innerHTML=`<input id="realDataOnly" type="checkbox"><span id="realDataOnlyLabel"></span>`;controls.appendChild(l);l.querySelector("input").addEventListener("change",()=>document.body.classList.toggle("real-data-only",l.querySelector("input").checked));const observer=new MutationObserver(decorateRanking);observer.observe(document.querySelector("#cards"),{childList:true,subtree:true});decorateRanking();}
  function decorateRanking(){document.querySelectorAll("#cards article").forEach((card,i)=>{if(card.querySelector(".trust-badge"))return;const s=songs[i];if(!s)return;const real=Math.min(Number(s.realRecommendationTotal||0),Number(s.realOverseasTotal||0));const state=s.seedBaseline?t("trustRef"):(real>=10?t("trustReal"):t("trustCollecting"));const level=real>=30?t("high"):(real>=10?t("medium"):t("low"));card.classList.toggle("reference-card",Boolean(s.seedBaseline));card.insertAdjacentHTML("afterbegin",`<p class="trust-badge">${state} · ${t("confidence")}: ${level}</p>`);card.insertAdjacentHTML("beforeend",`<button class="text-button quality-report-button" type="button" data-quality-report="${Number(s.id)}">${t("report")}</button>`);});}
  function installQualityReporting(){document.addEventListener("click",async e=>{const btn=e.target.closest("[data-quality-report]");if(!btn)return;const type=prompt("broken_video / wrong_video / wrong_metadata / wrong_image / duplicate / other","broken_video");if(!type)return;try{await rest("song_quality_reports",{method:"POST",authenticated:true,headers:{Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify({user_id:currentUser.id,song_id:Number(btn.dataset.qualityReport),report_type:type})});alert(t("reportSent"));}catch(err){alert(err.message);}});}

  function makeShareCard(title,subtitle){const c=document.createElement("canvas");c.width=1080;c.height=1350;const x=c.getContext("2d");x.fillStyle="#f4efe6";x.fillRect(0,0,c.width,c.height);x.fillStyle="#d7472f";x.fillRect(80,80,16,1190);x.fillStyle="#111";x.font="700 54px system-ui";x.fillText("JAPAN HIDDEN GEMS",130,180);x.font="700 76px system-ui";wrap(x,title,130,350,820,100);x.font="42px system-ui";x.fillStyle="#5f5a52";wrap(x,subtitle,130,790,820,60);x.font="700 38px system-ui";x.fillStyle="#d7472f";x.fillText("bokuwahaitaka.github.io/Japan-hidden-gems",130,1210);return c;}
  function wrap(ctx,text,x,y,max,line){const words=String(text).split(/\s+/);let row="";for(const w of words){const test=row+w+" ";if(ctx.measureText(test).width>max&&row){ctx.fillText(row,x,y);row=w+" ";y+=line;}else row=test;}ctx.fillText(row,x,y);}
  async function shareResult(download=false){const s=dailyState&&songs.find(x=>Number(x.id)===Number(dailyState.session.discovery_song_id));const title=s?`${songTitle(s)} — ${songArtist(s)}`:"My J-pop discovery";const c=makeShareCard(title,t("complete"));if(download){const a=document.createElement("a");a.download="jpop-discovery.png";a.href=c.toDataURL("image/png");a.click();return;}if(navigator.share)await navigator.share({title:"Japan Hidden Gems",text:title,url:location.origin+location.pathname+"?view=daily"});else{await navigator.clipboard.writeText(title+" "+location.origin+location.pathname+"?view=daily");}}

  const originalRender=renderView;renderView=function(view,options={}){originalRender(view,options);document.querySelectorAll("[data-growth-route]").forEach(x=>x.classList.toggle("is-active",x.dataset.growthRoute===view));if(view==="profile")profile();};
  const originalLanguage=setInterfaceLanguage;setInterfaceLanguage=function(lang,persist=true){originalLanguage(lang,persist);localize();decorateRanking();};
  document.addEventListener("click",e=>{if(e.target.id==="shareDaily")shareResult(false);if(e.target.id==="downloadDaily")shareResult(true);if(e.target.id==="shareCupChampion"&&cupState?.champion){const s=cupState.champion,title=`${songTitle(s)} — ${songArtist(s)}`;if(navigator.share)navigator.share({title:"J-POP Cup Champion",text:title,url:location.href});else navigator.clipboard.writeText(title+" "+location.href);}});
  document.addEventListener("DOMContentLoaded",install);
})();
