begin;

create table if not exists public.youtube_link_candidates (
  id bigint generated by default as identity primary key,
  song_id bigint not null references public.songs(id) on delete cascade,
  video_id text not null check (video_id ~ '^[A-Za-z0-9_-]{11}$'),
  youtube_url text not null,
  video_title text not null,
  channel_name text not null default '',
  confidence numeric(4,3) not null check (confidence between 0 and 1),
  official_signals text[] not null default '{}',
  status text not null default 'pending' check (status in ('pending','accepted','rejected')),
  checked_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null,
  unique (song_id, video_id)
);

create index if not exists youtube_link_candidates_pending_idx
  on public.youtube_link_candidates(status, confidence desc, checked_at desc);
create index if not exists youtube_link_candidates_song_idx
  on public.youtube_link_candidates(song_id, status);

alter table public.youtube_link_candidates enable row level security;
revoke all on table public.youtube_link_candidates from public, anon, authenticated;

create or replace function public.admin_list_youtube_link_candidates()
returns table (
  id bigint, song_id bigint, song_title text, song_artist text, video_id text,
  youtube_url text, video_title text, channel_name text, confidence numeric,
  official_signals text[], checked_at timestamptz
)
language plpgsql security definer set search_path = public, pg_temp
as $$
begin
  if auth.uid() is null or not public.is_song_admin() then
    raise exception 'Administrator access required.' using errcode = '42501';
  end if;
  return query
  select c.id, c.song_id, s.title, s.artist, c.video_id, c.youtube_url,
    c.video_title, c.channel_name, c.confidence, c.official_signals, c.checked_at
  from public.youtube_link_candidates c join public.songs s on s.id = c.song_id
  where c.status = 'pending'
  order by c.confidence desc, c.checked_at desc limit 200;
end;
$$;

create or replace function public.admin_review_youtube_link_candidate(p_candidate_id bigint, p_accept boolean)
returns boolean language plpgsql security definer set search_path = public, pg_temp
as $$
declare v_candidate public.youtube_link_candidates%rowtype;
begin
  if auth.uid() is null or not public.is_song_admin() then
    raise exception 'Administrator access required.' using errcode = '42501';
  end if;
  select * into v_candidate from public.youtube_link_candidates
  where id = p_candidate_id and status = 'pending' for update;
  if not found then return false; end if;
  update public.youtube_link_candidates
  set status = case when p_accept then 'accepted' else 'rejected' end,
      reviewed_at = now(), reviewed_by = auth.uid()
  where id = p_candidate_id;
  if p_accept then
    update public.songs
    set youtube_url = v_candidate.youtube_url, youtube_video_id = v_candidate.video_id,
        youtube_thumbnail_url = 'https://i.ytimg.com/vi/' || v_candidate.video_id || '/hqdefault.jpg',
        youtube_status = 'valid', youtube_checked_at = now(), media_enrichment_status = 'ready',
        media_match_confidence = v_candidate.confidence, media_source = 'youtube-public-search',
        media_enriched_at = now()
    where id = v_candidate.song_id;
    update public.youtube_link_candidates
    set status = 'rejected', reviewed_at = now(), reviewed_by = auth.uid()
    where song_id = v_candidate.song_id and id <> v_candidate.id and status = 'pending';
  end if;
  return true;
end;
$$;

revoke all on function public.admin_list_youtube_link_candidates() from public;
revoke all on function public.admin_review_youtube_link_candidate(bigint, boolean) from public;
revoke all on function public.admin_list_youtube_link_candidates() from anon;
revoke all on function public.admin_review_youtube_link_candidate(bigint, boolean) from anon;
grant execute on function public.admin_list_youtube_link_candidates() to authenticated;
grant execute on function public.admin_review_youtube_link_candidate(bigint, boolean) to authenticated;

commit;
