-- Daily discovery, listening profile data and song quality controls.
create table if not exists public.daily_discovery_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  challenge_date date not null default current_date,
  song_ids bigint[] not null check (cardinality(song_ids)=5),
  discovery_song_id bigint references public.songs(id) on delete set null,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  unique(user_id,challenge_date)
);
create table if not exists public.daily_discovery_responses (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.daily_discovery_sessions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  song_id bigint not null references public.songs(id) on delete cascade,
  heard_before boolean not null,
  rating smallint check(rating between 1 and 5),
  created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
  unique(session_id,song_id)
);
create table if not exists public.song_quality_reports (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  song_id bigint not null references public.songs(id) on delete cascade,
  report_type text not null check(report_type in ('broken_video','wrong_video','wrong_metadata','wrong_image','duplicate','other')),
  message text check(message is null or char_length(message)<=1000),
  status text not null default 'pending' check(status in ('pending','reviewed','resolved','dismissed')),
  admin_note text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),
  unique(user_id,song_id,report_type)
);
alter table public.songs add column if not exists normalized_title text;
alter table public.songs add column if not exists normalized_artist text;
alter table public.songs add column if not exists youtube_status text not null default 'unchecked';
alter table public.songs add column if not exists youtube_checked_at timestamptz;
alter table public.songs add column if not exists ai_tag_confidence numeric(4,3);
alter table public.songs add column if not exists data_quality_status text not null default 'unreviewed';
alter table public.tournament_runs add column if not exists entrant_song_ids bigint[];
alter table public.tournament_runs add column if not exists share_token uuid not null default gen_random_uuid();
create unique index if not exists tournament_runs_share_token_uidx on public.tournament_runs(share_token);
create index if not exists daily_discovery_sessions_user_date_idx on public.daily_discovery_sessions(user_id,challenge_date desc);
create index if not exists daily_discovery_responses_user_created_idx on public.daily_discovery_responses(user_id,created_at desc);
create index if not exists daily_discovery_responses_song_idx on public.daily_discovery_responses(song_id);
create index if not exists song_quality_reports_status_created_idx on public.song_quality_reports(status,created_at desc);
create index if not exists song_quality_reports_song_idx on public.song_quality_reports(song_id);
create index if not exists songs_normalized_identity_idx on public.songs(normalized_artist,normalized_title);
create index if not exists songs_youtube_status_idx on public.songs(youtube_status,youtube_checked_at);
alter table public.daily_discovery_sessions enable row level security;
alter table public.daily_discovery_responses enable row level security;
alter table public.song_quality_reports enable row level security;
create policy daily_sessions_select_own on public.daily_discovery_sessions for select to authenticated using((select auth.uid())=user_id);
create policy daily_sessions_insert_own on public.daily_discovery_sessions for insert to authenticated with check((select auth.uid())=user_id);
create policy daily_sessions_update_own on public.daily_discovery_sessions for update to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
create policy daily_responses_select_own on public.daily_discovery_responses for select to authenticated using((select auth.uid())=user_id);
create policy daily_responses_insert_own on public.daily_discovery_responses for insert to authenticated with check((select auth.uid())=user_id and exists(select 1 from public.daily_discovery_sessions s where s.id=session_id and s.user_id=(select auth.uid())));
create policy daily_responses_update_own on public.daily_discovery_responses for update to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
create policy quality_reports_select_own_or_admin on public.song_quality_reports for select to authenticated using((select auth.uid())=user_id or public.is_song_admin());
create policy quality_reports_insert_own on public.song_quality_reports for insert to authenticated with check((select auth.uid())=user_id);
create policy quality_reports_admin_update on public.song_quality_reports for update to authenticated using(public.is_song_admin()) with check(public.is_song_admin());
revoke all on public.daily_discovery_sessions,public.daily_discovery_responses,public.song_quality_reports from public,anon;
grant select,insert,update on public.daily_discovery_sessions,public.daily_discovery_responses,public.song_quality_reports to authenticated;
