-- Reproducible baseline for the tables that predate the checked-in migrations.
begin;

create table if not exists public.songs (
  id bigint generated by default as identity primary key,
  title text not null,
  artist text not null,
  year smallint not null,
  youtube_url text
);

create table if not exists public.recommendations (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  song_id bigint references public.songs(id) on delete cascade,
  recommended boolean,
  user_id uuid references auth.users(id) on delete cascade,
  updated_at timestamptz default now()
);

create table if not exists public.ratings (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  heard_before boolean not null,
  rating smallint,
  song_id bigint not null references public.songs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  updated_at timestamptz default now(),
  constraint ratings_initial_value_check check (
    (heard_before and rating is null)
    or (not heard_before and (rating is null or rating between 1 and 5))
  )
);

create table if not exists public.song_seed_metrics (
  song_id bigint primary key references public.songs(id) on delete cascade,
  recommendation_total integer not null check (recommendation_total >= 0),
  recommendation_count integer not null check (
    recommendation_count >= 0 and recommendation_count <= recommendation_total
  ),
  overseas_total integer not null check (overseas_total >= 0),
  known_count integer not null check (
    known_count >= 0 and known_count <= overseas_total
  ),
  post_listen_rating_count integer not null check (
    post_listen_rating_count >= 0 and post_listen_rating_count <= overseas_total
  ),
  average_rating numeric(3,2) not null check (average_rating between 1 and 5),
  created_at timestamptz not null default now()
);

create unique index if not exists recommendations_user_song_unique
  on public.recommendations(user_id,song_id) where user_id is not null;
create unique index if not exists ratings_user_song_unique_idx
  on public.ratings(user_id,song_id);
create index if not exists recommendations_song_id_idx on public.recommendations(song_id);
create index if not exists ratings_song_id_idx on public.ratings(song_id);

alter table public.songs enable row level security;
alter table public.recommendations enable row level security;
alter table public.ratings enable row level security;
alter table public.song_seed_metrics enable row level security;

drop policy if exists songs_public_read on public.songs;
create policy songs_public_read on public.songs for select to anon,authenticated using (true);

drop policy if exists recommendations_authenticated_read on public.recommendations;
create policy recommendations_authenticated_read on public.recommendations
  for select to authenticated using (true);
drop policy if exists recommendations_insert_own on public.recommendations;
create policy recommendations_insert_own on public.recommendations
  for insert to authenticated with check ((select auth.uid())=user_id);
drop policy if exists recommendations_update_own on public.recommendations;
create policy recommendations_update_own on public.recommendations
  for update to authenticated using ((select auth.uid())=user_id)
  with check ((select auth.uid())=user_id);
drop policy if exists recommendations_delete_own on public.recommendations;
create policy recommendations_delete_own on public.recommendations
  for delete to authenticated using ((select auth.uid())=user_id);

drop policy if exists ratings_authenticated_read on public.ratings;
create policy ratings_authenticated_read on public.ratings
  for select to authenticated using (true);
drop policy if exists ratings_insert_own on public.ratings;
create policy ratings_insert_own on public.ratings
  for insert to authenticated with check ((select auth.uid())=user_id);
drop policy if exists ratings_update_own on public.ratings;
create policy ratings_update_own on public.ratings
  for update to authenticated using ((select auth.uid())=user_id)
  with check ((select auth.uid())=user_id);
drop policy if exists ratings_delete_own on public.ratings;
create policy ratings_delete_own on public.ratings
  for delete to authenticated using ((select auth.uid())=user_id);

revoke all on public.songs,public.recommendations,public.ratings,public.song_seed_metrics from public;
grant select on public.songs to anon,authenticated;
grant select,insert,update,delete on public.recommendations,public.ratings to authenticated;

commit;
