-- Reproducible baseline for feature tables that were originally created outside
-- this repository. This runs after song_tags and before the 20260823 extensions.
begin;

create table if not exists public.playlists (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 50),
  description text not null default '' check (char_length(description) <= 240),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id,name)
);

create table if not exists public.playlist_songs (
  playlist_id bigint not null references public.playlists(id) on delete cascade,
  song_id bigint not null references public.songs(id) on delete cascade,
  position integer not null default 0 check (position >= 0),
  added_at timestamptz not null default now(),
  primary key(playlist_id,song_id)
);

create table if not exists public.listening_history (
  user_id uuid not null references auth.users(id) on delete cascade,
  song_id bigint not null references public.songs(id) on delete cascade,
  first_opened_at timestamptz not null default now(),
  last_opened_at timestamptz not null default now(),
  open_count integer not null default 1 check (open_count > 0),
  primary key(user_id,song_id)
);

create table if not exists public.feedback_box (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null check (category in ('feature','bug','song','content','other')),
  message text not null check (char_length(trim(message)) between 10 and 2000),
  locale text not null default 'en' check (locale in ('ja','en','ko','zh','ru','es','fr')),
  page_context text check (page_context is null or char_length(page_context) <= 200),
  status text not null default 'pending' check (status in ('pending','reviewed','planned','resolved','closed')),
  admin_note text check (admin_note is null or char_length(admin_note) <= 2000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tournament_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  mode text not null,
  tag_id bigint references public.song_tags(id) on delete set null,
  bracket_size smallint not null default 8 check (bracket_size in (4,8,16)),
  champion_song_id bigint references public.songs(id) on delete set null,
  status text not null default 'active' check (status in ('active','completed','abandoned')),
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint tournament_runs_mode_check check (mode in ('random','tag')),
  constraint tournament_runs_mode_tag_check check (
    (mode='tag' and tag_id is not null) or (mode<>'tag' and tag_id is null)
  ),
  constraint tournament_runs_completion_check check (
    (status='completed' and champion_song_id is not null and completed_at is not null)
    or status<>'completed'
  )
);

create table if not exists public.tournament_votes (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.tournament_runs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  round_number smallint not null check (round_number between 1 and 4),
  match_number smallint not null check (match_number between 1 and 8),
  song_a_id bigint not null references public.songs(id) on delete cascade,
  song_b_id bigint not null references public.songs(id) on delete cascade,
  winner_song_id bigint not null references public.songs(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint tournament_votes_distinct_songs check (song_a_id<>song_b_id),
  constraint tournament_votes_valid_winner check (winner_song_id in (song_a_id,song_b_id)),
  constraint tournament_votes_one_match unique(run_id,round_number,match_number)
);

create index if not exists playlists_user_updated_idx on public.playlists(user_id,updated_at desc);
create index if not exists playlist_songs_playlist_position_idx on public.playlist_songs(playlist_id,position,added_at);
create index if not exists playlist_songs_song_id_idx on public.playlist_songs(song_id);
create index if not exists listening_history_user_recent_idx on public.listening_history(user_id,last_opened_at desc);
create index if not exists listening_history_song_id_idx on public.listening_history(song_id);
create index if not exists feedback_box_user_created_idx on public.feedback_box(user_id,created_at desc);
create index if not exists feedback_box_admin_queue_idx on public.feedback_box(status,created_at desc)
  where status in ('pending','reviewed','planned');
create index if not exists tournament_runs_user_created_idx on public.tournament_runs(user_id,created_at desc);
create index if not exists tournament_runs_tag_idx on public.tournament_runs(tag_id) where tag_id is not null;
create index if not exists tournament_votes_run_idx on public.tournament_votes(run_id);

alter table public.playlists enable row level security;
alter table public.playlist_songs enable row level security;
alter table public.listening_history enable row level security;
alter table public.feedback_box enable row level security;
alter table public.tournament_runs enable row level security;
alter table public.tournament_votes enable row level security;

drop policy if exists playlists_own_all on public.playlists;
create policy playlists_own_all on public.playlists for all to authenticated
  using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
drop policy if exists playlist_songs_own_all on public.playlist_songs;
create policy playlist_songs_own_all on public.playlist_songs for all to authenticated
  using (exists(select 1 from public.playlists p where p.id=playlist_id and p.user_id=(select auth.uid())))
  with check (exists(select 1 from public.playlists p where p.id=playlist_id and p.user_id=(select auth.uid())));
drop policy if exists listening_history_own_all on public.listening_history;
create policy listening_history_own_all on public.listening_history for all to authenticated
  using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
drop policy if exists feedback_box_select_own on public.feedback_box;
create policy feedback_box_select_own on public.feedback_box for select to authenticated
  using ((select auth.uid())=user_id or public.is_song_admin());
drop policy if exists feedback_box_insert_own on public.feedback_box;
create policy feedback_box_insert_own on public.feedback_box for insert to authenticated
  with check ((select auth.uid())=user_id);
drop policy if exists tournament_runs_own_all on public.tournament_runs;
create policy tournament_runs_own_all on public.tournament_runs for all to authenticated
  using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
drop policy if exists tournament_votes_own_all on public.tournament_votes;
create policy tournament_votes_own_all on public.tournament_votes for all to authenticated
  using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);

revoke all on public.playlists,public.playlist_songs,public.listening_history,public.feedback_box,public.tournament_runs,public.tournament_votes from public,anon;
grant select,insert,update,delete on public.playlists,public.playlist_songs,public.listening_history,public.feedback_box,public.tournament_runs,public.tournament_votes to authenticated;

commit;
